const API="https://ep-holy-sky-b5qingk3.apirest.c-7.us-east-2.aws.neon.tech/neondb/rest/v1";
let db={vehicle:null,fuel:[],maint:[],exp:[]};
let legacy={vehicle:null,fuel:[],maint:[],exp:[]};
try{legacy=JSON.parse(localStorage.getItem("moto_v2")||localStorage.getItem("moto_v1"))||legacy}catch(e){}
function today(){return new Date().toISOString().slice(0,10)}
function money(n){return Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function dateBR(s){return s?new Date(s+"T12:00:00").toLocaleDateString("pt-BR"):"—"}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function currentKm(){return Math.max(db.vehicle?.ikm||0,...db.fuel.map(x=>+x.km||0),...db.maint.map(x=>+x.km||0),...db.exp.map(x=>+x.km||0))}
function toast(s){const x=document.getElementById("toast");if(!x)return;x.textContent=s;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1600)}
function nav(active){document.querySelectorAll(".nav a").forEach(a=>a.classList.toggle("on",a.dataset.p===active))}
function fuelFromApi(x){return{id:x.id,date:x.entry_date,km:+x.km,total:+x.total_amount,pl:+x.price_per_liter,liters:+x.liters,type:x.fuel_type||"",station:x.station||"",notes:x.notes||"",distance:x.distance_km==null?null:+x.distance_km,consumption:x.consumption_km_l==null?null:+x.consumption_km_l}}
function maintFromApi(x){return{id:x.id,date:x.entry_date,km:+x.km,item:x.item,price:+x.price,type:x.maintenance_type||"",store:x.store||"",phone:x.phone||"",nextKm:x.next_km==null?null:+x.next_km,nextDate:x.next_date||"",notes:x.notes||""}}
function expFromApi(x){return{id:x.id,date:x.entry_date,km:+x.km,cat:x.category,price:+x.price,desc:x.description,notes:x.notes||""}}
function vehicleFromApi(x){return x?{brand:x.brand,model:x.model,yf:+x.year_fabrication,ym:+x.year_model,plate:x.plate||"",ikm:+x.initial_km,ft:x.fuel_type||"Gasolina",notes:x.notes||""}:null}
async function api(table,options={}){const r=await fetch(API+"/"+table,{headers:{Accept:"application/json","Content-Type":"application/json",...(options.headers||{})},...options});const data=await r.json().catch(()=>[]);if(!r.ok)throw new Error(data?.message||data?.error||"Falha no Neon Data API");return data}
async function bootstrap(){const [v,f,m,e]=await Promise.all([api("moto_vehicle?order=updated_at.desc&limit=1"),api("moto_fuel?order=km.asc"),api("moto_maintenance?order=km.asc"),api("moto_expense?order=entry_date.asc,created_at.asc")]);return{vehicle:v[0]||null,fuel:f,maint:m,exp:e}}
async function migrateLocal(){if(legacy.vehicle){await api("moto_vehicle",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({brand:legacy.vehicle.brand,model:legacy.vehicle.model,year_fabrication:legacy.vehicle.yf,year_model:legacy.vehicle.ym,plate:legacy.vehicle.plate||null,initial_km:+legacy.vehicle.ikm||0,fuel_type:legacy.vehicle.ft||null,notes:legacy.vehicle.notes||null})})}for(const x of legacy.fuel)await createFuel(x);for(const x of legacy.maint)await createMaintenance(x);for(const x of legacy.exp)await createExpense(x)}
async function loadRemote(){try{let remote=await bootstrap();const hasRemote=!!remote.vehicle||remote.fuel.length||remote.maint.length||remote.exp.length;const hasLegacy=!!legacy.vehicle||legacy.fuel.length||legacy.maint.length||legacy.exp.length;if(!hasRemote&&hasLegacy){await migrateLocal();remote=await bootstrap()}db={vehicle:vehicleFromApi(remote.vehicle),fuel:remote.fuel.map(fuelFromApi),maint:remote.maint.map(maintFromApi),exp:remote.exp.map(expFromApi)};localStorage.removeItem("moto_v2");localStorage.removeItem("moto_v1");window.dispatchEvent(new CustomEvent("moto:ready"));return true}catch(e){console.error("Neon Data API:",e);window.dispatchEvent(new CustomEvent("moto:error",{detail:e}));return false}}
async function saveVehicle(v){await api("moto_vehicle",{method:"DELETE",headers:{Prefer:"return=minimal"}});const rows=await api("moto_vehicle",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({brand:v.brand,model:v.model,year_fabrication:v.yf,year_model:v.ym,plate:v.plate||null,initial_km:+v.ikm||0,fuel_type:v.ft||null,notes:v.notes||null})});db.vehicle=vehicleFromApi(rows[0])}
async function createFuel(v){const previous=db.fuel.slice().sort((a,b)=>b.km-a.km)[0];const total=+v.total,pl=+v.pl,liters=total/pl;const distance=previous?+v.km-previous.km:null;const consumption=previous&&liters?distance/liters:null;const rows=await api("moto_fuel",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({entry_date:v.date,km:+v.km,total_amount:total,price_per_liter:pl,liters,fuel_type:v.type||null,station:v.station||null,notes:v.notes||null,distance_km:distance,consumption_km_l:consumption})});const x=fuelFromApi(rows[0]);db.fuel.push(x);db.fuel.sort((a,b)=>a.km-b.km);return x}
async function createMaintenance(v){const rows=await api("moto_maintenance",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({entry_date:v.date,km:+v.km,item:v.item,price:+v.price,maintenance_type:v.type||null,store:v.store||null,phone:v.phone||null,next_km:v.nextKm?+v.nextKm:null,next_date:v.nextDate||null,notes:v.notes||null})});const x=maintFromApi(rows[0]);db.maint.push(x);db.maint.sort((a,b)=>a.km-b.km);return x}
async function createExpense(v){const rows=await api("moto_expense",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({entry_date:v.date,km:+v.km||0,category:v.cat,price:+v.price,description:v.desc,notes:v.notes||null})});const x=expFromApi(rows[0]);db.exp.push(x);return x}
async function del(type,id){if(!confirm("Excluir este registro?"))return;const table=type==="fuel"?"moto_fuel":type==="maint"?"moto_maintenance":"moto_expense";try{await api(table+"?id=eq."+encodeURIComponent(id),{method:"DELETE",headers:{Prefer:"return=minimal"}});db[type]=db[type].filter(x=>x.id!==id);location.reload()}catch(e){toast("Não foi possível excluir")}}
loadRemote();
