const API="https://ep-holy-sky-b5qingk3.apirest.c-7.us-east-2.aws.neon.tech/neondb/rest/v1";
const AUTH="https://ep-jolly-bonus-b4gg5qtb.neonauth.c-6.us-east-2.aws.neon.tech/neondb/auth";
let client=null, records=[], editingId=null, busy=false;

const $=s=>document.querySelector(s);
const form=$("#fuelForm"), saveBtn=$("#saveBtn"), cancelBtn=$("#cancelBtn"), statusEl=$("#status"), formTitle=$("#formTitle");

function money(n){return Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function num(n,d=2){return Number(n||0).toLocaleString("pt-BR",{minimumFractionDigits:d,maximumFractionDigits:d})}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function dateInputValue(d=new Date()){const x=new Date(d);const pad=n=>String(n).padStart(2,"0");return x.getFullYear()+"-"+pad(x.getMonth()+1)+"-"+pad(x.getDate())}
function dateBR(v){if(!v)return "—";return new Date(v).toLocaleDateString("pt-BR")}
async function setUpdated(){try{const r=await fetch("https://api.github.com/repos/leorbr27/Moto/commits/main",{headers:{Accept:"application/vnd.github+json"}});if(!r.ok)throw new Error("GitHub "+r.status);const c=await r.json();const d=new Date(c.commit?.committer?.date||c.commit?.author?.date);if(Number.isNaN(d.getTime()))throw new Error("Data de commit inválida");$("#updatedAt").textContent=d.toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"})}catch(e){$("#updatedAt").textContent="indisponível";console.error("Diagnóstico GitHub:",e)}}
function toast(msg){const x=$("#toast");x.textContent=msg;x.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove("show"),3500)}
function setStatus(msg,type="info"){if(!msg){statusEl.hidden=true;return}statusEl.hidden=false;statusEl.className="status "+type;statusEl.textContent=msg}
function showError(msg){console.error(msg);setStatus(msg,"error");toast(msg)}
async function getClient(){if(client)return client;const mod=await import("https://esm.sh/@neondatabase/neon-js@latest");client=mod.createClient({auth:{adapter:mod.BetterAuthVanillaAdapter(),url:AUTH,allowAnonymous:false},dataApi:{url:API}});return client}
async function requireSession(){const c=await getClient();const session=await c.auth.getSession();if(!session?.data?.session){location.replace("auth.html");throw new Error("Sessão não autenticada.")}return c}
async function token(){const c=await requireSession();const t=await c.auth.getJWTToken();if(!t)throw new Error("Não foi possível obter o token autenticado do Neon.");return t}
async function api(path,options={}){const t=await token();const r=await fetch(API+"/"+path,{...options,headers:{Accept:"application/json","Content-Type":"application/json",Authorization:"Bearer "+t,...(options.headers||{})}});const raw=await r.text();let data=[];try{data=raw?JSON.parse(raw):[]}catch{}if(!r.ok){const detail=data?.message||data?.error||raw||r.statusText;throw new Error("Neon "+r.status+": "+detail)}return data}
async function load(){setStatus("Consultando os abastecimentos no Neon…");try{records=await api("abastecimentos?select=*&order=data_abastecimento.desc,created_at.desc");records=records.map(normalize);render();setUpdated();setStatus("");}catch(e){showError("Não foi possível carregar os dados do Neon. Tente novamente.");console.error("Diagnóstico Neon:",e)}}
function normalize(x){return{...x,km:Number(x.quilometragem),liters:Number(x.litros),total:Number(x.valor_total),price:Number(x.preco_litro)}}
function recalcLiters(){const total=Number(form.total.value),price=Number(form.price.value);form.liters.value=total>0&&price>0?(total/price).toFixed(3):""}
function lastRecord(){return records.slice().sort((a,b)=>new Date(b.data_abastecimento)-new Date(a.data_abastecimento))[0]}
function resetForm(copyLast=true){editingId=null;form.reset();form.date.value=dateInputValue();formTitle.textContent="Novo abastecimento";saveBtn.textContent="💾 Salvar abastecimento";cancelBtn.hidden=true;const last=copyLast?lastRecord():null;if(last){form.km.value=last.km??"";form.total.value=last.total??"";form.price.value=last.price??"";form.fuel.value=last.combustivel||form.fuel.value;form.station.value=last.posto||"";form.notes.value=last.observacoes||"";recalcLiters()}else form.liters.value=""}
function editRecord(id){const x=records.find(r=>r.id===id);if(!x)return;editingId=id;form.date.value=dateInputValue(new Date(x.data_abastecimento));form.km.value=x.km;form.total.value=x.total;form.price.value=x.price;form.liters.value=x.liters.toFixed(3);form.fuel.value=x.combustivel||"Gasolina comum";form.station.value=x.posto||"";form.notes.value=x.observacoes||"";formTitle.textContent="Editar abastecimento";saveBtn.textContent="💾 Salvar alterações";cancelBtn.hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
function payload(){return{data_abastecimento:new Date(form.date.value+"T12:00:00").toISOString(),quilometragem:Number(form.km.value),litros:Number(form.liters.value),valor_total:Number(form.total.value),preco_litro:Number(form.price.value),combustivel:form.fuel.value,posto:form.station.value.trim()||null,observacoes:form.notes.value.trim()||null}}
function validate(p){if(!form.date.value||Number.isNaN(new Date(form.date.value+"T12:00:00").getTime()))return"Informe uma data válida.";if(!Number.isFinite(p.quilometragem)||p.quilometragem<0)return"Informe uma quilometragem válida.";if(!Number.isFinite(p.valor_total)||p.valor_total<=0)return"Informe o valor abastecido.";if(!Number.isFinite(p.preco_litro)||p.preco_litro<=0)return"Informe o preço por litro.";if(!Number.isFinite(p.litros)||p.litros<=0)return"Não foi possível calcular os litros.";if(!p.combustivel)return"Informe o combustível.";const ordered=records.filter(r=>r.id!==editingId).sort((a,b)=>a.km-b.km);const previous=ordered.filter(r=>r.km<=p.quilometragem).at(-1);if(!editingId&&previous&&p.quilometragem<previous.km)return"A quilometragem não pode ser menor que a anterior.";return null}
async function save(e){e.preventDefault();if(busy)return;recalcLiters();const p=payload(),err=validate(p);if(err){showError(err);return}busy=true;saveBtn.disabled=true;setStatus(editingId?"Salvando alterações…":"Salvando abastecimento…");try{let data;if(editingId){data=await api("abastecimentos?id=eq."+encodeURIComponent(editingId),{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({...p,updated_at:new Date().toISOString()})});if(!data[0])throw new Error("Registro não encontrado.");records=records.map(r=>r.id===editingId?normalize(data[0]):r)}else{data=await api("abastecimentos",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(p)});if(!data[0])throw new Error("A API não retornou o registro salvo.");records.unshift(normalize(data[0]))}records.sort((a,b)=>new Date(b.data_abastecimento)-new Date(a.data_abastecimento));render();resetForm(true);setUpdated();setStatus("");toast(editingId?"Abastecimento atualizado com sucesso.":"Abastecimento salvo com sucesso.");editingId=null}catch(e){showError(editingId?"Não foi possível atualizar o abastecimento.":"Não foi possível salvar o abastecimento.");console.error("Diagnóstico de gravação Neon:",e)}finally{busy=false;saveBtn.disabled=false}}
async function removeRecord(id){if(busy)return;const x=records.find(r=>r.id===id);if(!x)return;if(!confirm("Excluir este abastecimento?

Esta ação não poderá ser desfeita."))return;busy=true;setStatus("Excluindo abastecimento…");try{await api("abastecimentos?id=eq."+encodeURIComponent(id),{method:"DELETE",headers:{Prefer:"return=minimal"}});records=records.filter(r=>r.id!==id);render();setUpdated();setStatus("");toast("Abastecimento excluído com sucesso.")}catch(e){showError("Não foi possível excluir o abastecimento.");console.error("Diagnóstico de exclusão Neon:",e)}finally{busy=false}}
function render(){const list=$("#fuelList");const sorted=records.slice().sort((a,b)=>new Date(b.data_abastecimento)-new Date(a.data_abastecimento));$("#countLabel").textContent=sorted.length?sorted.length+" registro"+(sorted.length===1?"":"s"):"";if(!sorted.length){list.innerHTML='<div class="empty">Nenhum abastecimento cadastrado.</div>'}else list.innerHTML=sorted.map(x=>'<article class="fuel-item"><div class="fuel-main"><div><div class="fuel-date">'+esc(dateBR(x.data_abastecimento))+'</div><div class="fuel-meta">'+num(x.km,0)+' km · '+esc(x.posto||"Posto não informado")+' · '+esc(x.combustivel||"Combustível não informado")+'<br>'+num(x.liters,2)+' L × '+money(x.price)+'/L'+(x.observacoes?"<br>"+esc(x.observacoes):"")+'</div></div><div class="fuel-total">'+money(x.total)+'</div></div><div class="fuel-actions"><button class="btn edit" data-edit="'+esc(x.id)+'">✏️ Editar</button><button class="btn danger" data-delete="'+esc(x.id)+'">🗑️ Excluir</button></div></article>').join("");list.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editRecord(b.dataset.edit));list.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>removeRecord(b.dataset.delete));renderMetrics()}
function renderMetrics(){const sorted=records.slice().sort((a,b)=>a.km-b.km);const total=records.reduce((s,x)=>s+x.total,0),liters=records.reduce((s,x)=>s+x.liters,0);let distance=0,validLiters=0;for(let i=1;i<sorted.length;i++){const d=sorted[i].km-sorted[i-1].km;if(d>0){distance+=d;validLiters+=sorted[i].liters}}const avg=validLiters?distance/validLiters:0;const costKm=distance>0?total/distance:0;const last=records.slice().sort((a,b)=>new Date(b.data_abastecimento)-new Date(a.data_abastecimento))[0];$("#metrics").innerHTML=[["KM atual",sorted.length?num(sorted.at(-1).km,0)+" km":"—"],["Último preço",last?money(last.price):"—"],["Consumo médio",avg?num(avg,1)+" km/L":"—"],["Custo médio/km",costKm?money(costKm):"—"]].map(([l,v])=>'<div class="metric"><div class="label">'+l+'</div><div class="value">'+v+'</div></div>').join("")}
form.total.addEventListener("input",recalcLiters);form.price.addEventListener("input",recalcLiters);cancelBtn.onclick=()=>resetForm(true);form.onsubmit=save;resetForm(true);(async()=>{await requireSession();await setUpdated();await load()})().catch(e=>console.error("Inicialização:",e));
